# Site settings
title: "News from London"
email: matteo.gildone@gmail.com
description: "A daily journal by Edward Hyde."
baseurl: "/london-news"
url: "http://localhost:4000"
twitter_username: domsmasher
github_username:  domsmasher

# Build settings
markdown: rdiscount
rdiscount:
 extensions: [smart]
permalink: /articles/:title
paginate: 3
